#!/bin/bash
##!/bin/sh

#export PATH=$PATH:/home/iwabuchiken/ws/ws_eclipse/G_nbp_new
#echo "New path set => /home/iwabuchiken/ws/ws_eclipse/G_nbp_new"

#echo $PATH

#echo cd ./ws

#java /home/iwabuchiken/ws/ws_eclipse/Time_calculator/bin/p1/E_5_multiple_sources

#################### Global vars
FM_HOME="/home/iwabuchiken/works/ws/FM"

#################### Function: show_bash()
show_bash() {
	echo export PATH=\$PATH:/home/iwabuchiken/works/PROGRAMS/bin:/home/iwabuchiken/works/PROGRAMS/G_nbp_new

}

#################### Function: show_git()
show_git() {
	echo git pull git@github.com:iwabuchiken/FM.git
	echo git reset --hard ORIG_HEAD
	echo git tag -a XXXX
	echo git push origin master
	echo git config --global alias.s status
}

#################### Function: show_fm()
show_fm() {
#	echo pushd /home/iwabuchiken/ws/FM
#	echo gitk \&
	pushd $FM_HOME
	gitk &
}

#################### Function: show_help()
show_help() {

	echo \<Usage\>
	echo 	"	aa [Options]"
	echo \<Options\>
	echo "	b	Show bash-related commands"
	echo "	fm	Show Freemind-related commands"
	echo "	fm2	Git pull FM"
	echo "	git	Show git-related commands"
	echo "	main	Show main commands"
	echo "	-h	Show help"

}

#################### Function: update_fm()
update_fm() {
#	FM_HOME="/home/iwabuchiken/works/ws/FM"
	echo "Entering $FM_HOME"
#	echo "Entering ws/FM/"
#	pushd "$FM_HOME"
	pushd $FM_HOME

	#debug
#	exit 0

	echo "Git-pulling remote"
	git pull git@github.com:iwabuchiken/FM.git
	popd
	echo "Update FM => Done"

}

#################### Function: show_main()
show_main() {

	echo cd ~/works/PROGRAMS/bin
	echo cd ~/works/ws
}


#################### Show infos
if [ "$1" == "git" ]; then
	
	show_git
	
	exit 0
elif [ "$1" == "fm" ]; then

	show_fm

	exit 0
elif [ "$1" == "fm2" ]; then

	update_fm

	exit 0

elif [ "$1" == "b" ]; then

	show_bash

	exit 0

elif [ "$1" == "main" ]; then

	show_main

	exit 0

elif [ "$1" == "-h" ]; then

	show_help

	exit 0

fi


#################### Start programs
# On the character "&" => http://itpro.nikkeibp.co.jp/article/COLUMN/20060228/231027/
#echo /home/iwabuchiken/ws/ws_eclipse/TC2/build/jar/TC2.jar &
#/home/iwabuchiken/ws/ws_eclipse/TC2/build/jar/TC2.jar &
echo /home/iwabuchiken/ws/ws_eclipse/TC2/build/release/TC2.jar &
/home/iwabuchiken/ws/ws_eclipse/TC2/build/release/TC2.jar &

echo /usr/bin/freemind &
/usr/bin/freemind &

echo /usr/bin/eclipse &
/usr/bin/eclipse &

#################### Show commands
echo cd /home/iwabuchiken/ws/FM
echo git pull git@github.com:iwabuchiken/FM.git

